// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Void Function(ffi.Pointer<glslang_version_t>)>()
external void glslang_get_version(ffi.Pointer<glslang_version_t> version);

@ffi.Native<ffi.Int Function()>()
external int glslang_initialize_process();

@ffi.Native<ffi.Void Function()>()
external void glslang_finalize_process();

@ffi.Native<
  ffi.Pointer<glslang_shader_t> Function(ffi.Pointer<glslang_input_t>)
>()
external ffi.Pointer<glslang_shader_t> glslang_shader_create(
  ffi.Pointer<glslang_input_t> input,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<glslang_shader_t>)>()
external void glslang_shader_delete(ffi.Pointer<glslang_shader_t> shader);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<glslang_shader_t>, ffi.Pointer<ffi.Char>)
>()
external void glslang_shader_set_preamble(
  ffi.Pointer<glslang_shader_t> shader,
  ffi.Pointer<ffi.Char> s,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<glslang_shader_t>, ffi.Pointer<ffi.Char>)
>()
external void glslang_shader_set_entry_point(
  ffi.Pointer<glslang_shader_t> shader,
  ffi.Pointer<ffi.Char> s,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<glslang_shader_t>, ffi.Bool)>()
external void glslang_shader_set_invert_y(
  ffi.Pointer<glslang_shader_t> shader,
  bool y,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<glslang_shader_t>,
    ffi.UnsignedInt,
    ffi.UnsignedInt,
  )
>(symbol: 'glslang_shader_shift_binding')
external void _glslang_shader_shift_binding(
  ffi.Pointer<glslang_shader_t> shader,
  int res,
  int base,
);

void glslang_shader_shift_binding(
  ffi.Pointer<glslang_shader_t> shader,
  glslang_resource_type_t res,
  int base,
) => _glslang_shader_shift_binding(shader, res.value, base);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<glslang_shader_t>,
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.UnsignedInt,
  )
>(symbol: 'glslang_shader_shift_binding_for_set')
external void _glslang_shader_shift_binding_for_set(
  ffi.Pointer<glslang_shader_t> shader,
  int res,
  int base,
  int set,
);

void glslang_shader_shift_binding_for_set(
  ffi.Pointer<glslang_shader_t> shader,
  glslang_resource_type_t res,
  int base,
  int set,
) => _glslang_shader_shift_binding_for_set(shader, res.value, base, set);

@ffi.Native<ffi.Void Function(ffi.Pointer<glslang_shader_t>, ffi.Int)>()
external void glslang_shader_set_options(
  ffi.Pointer<glslang_shader_t> shader,
  int options,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<glslang_shader_t>, ffi.Int)>()
external void glslang_shader_set_glsl_version(
  ffi.Pointer<glslang_shader_t> shader,
  int version,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<glslang_shader_t>,
    ffi.UnsignedInt,
    ffi.UnsignedInt,
  )
>()
external void glslang_shader_set_default_uniform_block_set_and_binding(
  ffi.Pointer<glslang_shader_t> shader,
  int set,
  int binding,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<glslang_shader_t>, ffi.Pointer<ffi.Char>)
>()
external void glslang_shader_set_default_uniform_block_name(
  ffi.Pointer<glslang_shader_t> shader,
  ffi.Pointer<ffi.Char> name,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<glslang_shader_t>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.UnsignedInt,
  )
>()
external void glslang_shader_set_resource_set_binding(
  ffi.Pointer<glslang_shader_t> shader,
  ffi.Pointer<ffi.Pointer<ffi.Char>> bindings,
  int num_bindings,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<glslang_shader_t>, ffi.Pointer<glslang_input_t>)
>()
external int glslang_shader_preprocess(
  ffi.Pointer<glslang_shader_t> shader,
  ffi.Pointer<glslang_input_t> input,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<glslang_shader_t>, ffi.Pointer<glslang_input_t>)
>()
external int glslang_shader_parse(
  ffi.Pointer<glslang_shader_t> shader,
  ffi.Pointer<glslang_input_t> input,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<glslang_shader_t>)>()
external ffi.Pointer<ffi.Char> glslang_shader_get_preprocessed_code(
  ffi.Pointer<glslang_shader_t> shader,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<glslang_shader_t>, ffi.Pointer<ffi.Char>)
>()
external void glslang_shader_set_preprocessed_code(
  ffi.Pointer<glslang_shader_t> shader,
  ffi.Pointer<ffi.Char> code,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<glslang_shader_t>)>()
external ffi.Pointer<ffi.Char> glslang_shader_get_info_log(
  ffi.Pointer<glslang_shader_t> shader,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<glslang_shader_t>)>()
external ffi.Pointer<ffi.Char> glslang_shader_get_info_debug_log(
  ffi.Pointer<glslang_shader_t> shader,
);

@ffi.Native<ffi.Pointer<glslang_program_t> Function()>()
external ffi.Pointer<glslang_program_t> glslang_program_create();

@ffi.Native<ffi.Void Function(ffi.Pointer<glslang_program_t>)>()
external void glslang_program_delete(ffi.Pointer<glslang_program_t> program);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<glslang_program_t>,
    ffi.Pointer<glslang_shader_t>,
  )
>()
external void glslang_program_add_shader(
  ffi.Pointer<glslang_program_t> program,
  ffi.Pointer<glslang_shader_t> shader,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<glslang_program_t>, ffi.Int)>()
external int glslang_program_link(
  ffi.Pointer<glslang_program_t> program,
  int messages,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<glslang_program_t>,
    ffi.UnsignedInt,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
  )
>(symbol: 'glslang_program_add_source_text')
external void _glslang_program_add_source_text(
  ffi.Pointer<glslang_program_t> program,
  int stage,
  ffi.Pointer<ffi.Char> text,
  int len,
);

void glslang_program_add_source_text(
  ffi.Pointer<glslang_program_t> program,
  glslang_stage_t stage,
  ffi.Pointer<ffi.Char> text,
  int len,
) => _glslang_program_add_source_text(program, stage.value, text, len);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<glslang_program_t>,
    ffi.UnsignedInt,
    ffi.Pointer<ffi.Char>,
  )
>(symbol: 'glslang_program_set_source_file')
external void _glslang_program_set_source_file(
  ffi.Pointer<glslang_program_t> program,
  int stage,
  ffi.Pointer<ffi.Char> file,
);

void glslang_program_set_source_file(
  ffi.Pointer<glslang_program_t> program,
  glslang_stage_t stage,
  ffi.Pointer<ffi.Char> file,
) => _glslang_program_set_source_file(program, stage.value, file);

@ffi.Native<ffi.Int Function(ffi.Pointer<glslang_program_t>)>()
external int glslang_program_map_io(ffi.Pointer<glslang_program_t> program);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<glslang_program_t>,
    ffi.Pointer<glslang_resolver_t>,
    ffi.Pointer<glslang_mapper_t>,
  )
>()
external int glslang_program_map_io_with_resolver_and_mapper(
  ffi.Pointer<glslang_program_t> program,
  ffi.Pointer<glslang_resolver_t> resolver,
  ffi.Pointer<glslang_mapper_t> mapper,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<glslang_program_t>, ffi.UnsignedInt)>(
  symbol: 'glslang_program_SPIRV_generate',
)
external void _glslang_program_SPIRV_generate(
  ffi.Pointer<glslang_program_t> program,
  int stage,
);

void glslang_program_SPIRV_generate(
  ffi.Pointer<glslang_program_t> program,
  glslang_stage_t stage,
) => _glslang_program_SPIRV_generate(program, stage.value);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<glslang_program_t>,
    ffi.UnsignedInt,
    ffi.Pointer<glslang_spv_options_t>,
  )
>(symbol: 'glslang_program_SPIRV_generate_with_options')
external void _glslang_program_SPIRV_generate_with_options(
  ffi.Pointer<glslang_program_t> program,
  int stage,
  ffi.Pointer<glslang_spv_options_t> spv_options,
);

void glslang_program_SPIRV_generate_with_options(
  ffi.Pointer<glslang_program_t> program,
  glslang_stage_t stage,
  ffi.Pointer<glslang_spv_options_t> spv_options,
) => _glslang_program_SPIRV_generate_with_options(
  program,
  stage.value,
  spv_options,
);

@ffi.Native<ffi.Size Function(ffi.Pointer<glslang_program_t>)>()
external int glslang_program_SPIRV_get_size(
  ffi.Pointer<glslang_program_t> program,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<glslang_program_t>,
    ffi.Pointer<ffi.UnsignedInt>,
  )
>()
external void glslang_program_SPIRV_get(
  ffi.Pointer<glslang_program_t> program,
  ffi.Pointer<ffi.UnsignedInt> arg1,
);

@ffi.Native<
  ffi.Pointer<ffi.UnsignedInt> Function(ffi.Pointer<glslang_program_t>)
>()
external ffi.Pointer<ffi.UnsignedInt> glslang_program_SPIRV_get_ptr(
  ffi.Pointer<glslang_program_t> program,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<glslang_program_t>)>()
external ffi.Pointer<ffi.Char> glslang_program_SPIRV_get_messages(
  ffi.Pointer<glslang_program_t> program,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<glslang_program_t>)>()
external ffi.Pointer<ffi.Char> glslang_program_get_info_log(
  ffi.Pointer<glslang_program_t> program,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<glslang_program_t>)>()
external ffi.Pointer<ffi.Char> glslang_program_get_info_debug_log(
  ffi.Pointer<glslang_program_t> program,
);

@ffi.Native<ffi.Pointer<glslang_mapper_t> Function()>()
external ffi.Pointer<glslang_mapper_t> glslang_glsl_mapper_create();

@ffi.Native<ffi.Void Function(ffi.Pointer<glslang_mapper_t>)>()
external void glslang_glsl_mapper_delete(ffi.Pointer<glslang_mapper_t> mapper);

@ffi.Native<
  ffi.Pointer<glslang_resolver_t> Function(
    ffi.Pointer<glslang_program_t>,
    ffi.UnsignedInt,
  )
>(symbol: 'glslang_glsl_resolver_create')
external ffi.Pointer<glslang_resolver_t> _glslang_glsl_resolver_create(
  ffi.Pointer<glslang_program_t> program,
  int stage,
);

ffi.Pointer<glslang_resolver_t> glslang_glsl_resolver_create(
  ffi.Pointer<glslang_program_t> program,
  glslang_stage_t stage,
) => _glslang_glsl_resolver_create(program, stage.value);

@ffi.Native<ffi.Void Function(ffi.Pointer<glslang_resolver_t>)>()
external void glslang_glsl_resolver_delete(
  ffi.Pointer<glslang_resolver_t> resolver,
);

enum glslang_stage_t {
  GLSLANG_STAGE_VERTEX(0),
  GLSLANG_STAGE_TESSCONTROL(1),
  GLSLANG_STAGE_TESSEVALUATION(2),
  GLSLANG_STAGE_GEOMETRY(3),
  GLSLANG_STAGE_FRAGMENT(4),
  GLSLANG_STAGE_COMPUTE(5),
  GLSLANG_STAGE_RAYGEN(6),
  GLSLANG_STAGE_INTERSECT(7),
  GLSLANG_STAGE_ANYHIT(8),
  GLSLANG_STAGE_CLOSESTHIT(9),
  GLSLANG_STAGE_MISS(10),
  GLSLANG_STAGE_CALLABLE(11),
  GLSLANG_STAGE_TASK(12),
  GLSLANG_STAGE_MESH(13),
  GLSLANG_STAGE_COUNT(14);

  static const GLSLANG_STAGE_RAYGEN_NV = GLSLANG_STAGE_RAYGEN;
  static const GLSLANG_STAGE_INTERSECT_NV = GLSLANG_STAGE_INTERSECT;
  static const GLSLANG_STAGE_ANYHIT_NV = GLSLANG_STAGE_ANYHIT;
  static const GLSLANG_STAGE_CLOSESTHIT_NV = GLSLANG_STAGE_CLOSESTHIT;
  static const GLSLANG_STAGE_MISS_NV = GLSLANG_STAGE_MISS;
  static const GLSLANG_STAGE_CALLABLE_NV = GLSLANG_STAGE_CALLABLE;
  static const GLSLANG_STAGE_TASK_NV = GLSLANG_STAGE_TASK;
  static const GLSLANG_STAGE_MESH_NV = GLSLANG_STAGE_MESH;

  final int value;
  const glslang_stage_t(this.value);

  static glslang_stage_t fromValue(int value) => switch (value) {
    0 => GLSLANG_STAGE_VERTEX,
    1 => GLSLANG_STAGE_TESSCONTROL,
    2 => GLSLANG_STAGE_TESSEVALUATION,
    3 => GLSLANG_STAGE_GEOMETRY,
    4 => GLSLANG_STAGE_FRAGMENT,
    5 => GLSLANG_STAGE_COMPUTE,
    6 => GLSLANG_STAGE_RAYGEN,
    7 => GLSLANG_STAGE_INTERSECT,
    8 => GLSLANG_STAGE_ANYHIT,
    9 => GLSLANG_STAGE_CLOSESTHIT,
    10 => GLSLANG_STAGE_MISS,
    11 => GLSLANG_STAGE_CALLABLE,
    12 => GLSLANG_STAGE_TASK,
    13 => GLSLANG_STAGE_MESH,
    14 => GLSLANG_STAGE_COUNT,
    _ => throw ArgumentError('Unknown value for glslang_stage_t: $value'),
  };

  @override
  String toString() {
    if (this == GLSLANG_STAGE_RAYGEN)
      return "glslang_stage_t.GLSLANG_STAGE_RAYGEN, glslang_stage_t.GLSLANG_STAGE_RAYGEN_NV";
    if (this == GLSLANG_STAGE_INTERSECT)
      return "glslang_stage_t.GLSLANG_STAGE_INTERSECT, glslang_stage_t.GLSLANG_STAGE_INTERSECT_NV";
    if (this == GLSLANG_STAGE_ANYHIT)
      return "glslang_stage_t.GLSLANG_STAGE_ANYHIT, glslang_stage_t.GLSLANG_STAGE_ANYHIT_NV";
    if (this == GLSLANG_STAGE_CLOSESTHIT)
      return "glslang_stage_t.GLSLANG_STAGE_CLOSESTHIT, glslang_stage_t.GLSLANG_STAGE_CLOSESTHIT_NV";
    if (this == GLSLANG_STAGE_MISS)
      return "glslang_stage_t.GLSLANG_STAGE_MISS, glslang_stage_t.GLSLANG_STAGE_MISS_NV";
    if (this == GLSLANG_STAGE_CALLABLE)
      return "glslang_stage_t.GLSLANG_STAGE_CALLABLE, glslang_stage_t.GLSLANG_STAGE_CALLABLE_NV";
    if (this == GLSLANG_STAGE_TASK)
      return "glslang_stage_t.GLSLANG_STAGE_TASK, glslang_stage_t.GLSLANG_STAGE_TASK_NV";
    if (this == GLSLANG_STAGE_MESH)
      return "glslang_stage_t.GLSLANG_STAGE_MESH, glslang_stage_t.GLSLANG_STAGE_MESH_NV";
    return super.toString();
  }
}

enum glslang_stage_mask_t {
  GLSLANG_STAGE_VERTEX_MASK(1),
  GLSLANG_STAGE_TESSCONTROL_MASK(2),
  GLSLANG_STAGE_TESSEVALUATION_MASK(4),
  GLSLANG_STAGE_GEOMETRY_MASK(8),
  GLSLANG_STAGE_FRAGMENT_MASK(16),
  GLSLANG_STAGE_COMPUTE_MASK(32),
  GLSLANG_STAGE_RAYGEN_MASK(64),
  GLSLANG_STAGE_INTERSECT_MASK(128),
  GLSLANG_STAGE_ANYHIT_MASK(256),
  GLSLANG_STAGE_CLOSESTHIT_MASK(512),
  GLSLANG_STAGE_MISS_MASK(1024),
  GLSLANG_STAGE_CALLABLE_MASK(2048),
  GLSLANG_STAGE_TASK_MASK(4096),
  GLSLANG_STAGE_MESH_MASK(8192),
  GLSLANG_STAGE_MASK_COUNT(8193);

  static const GLSLANG_STAGE_RAYGEN_NV_MASK = GLSLANG_STAGE_RAYGEN_MASK;
  static const GLSLANG_STAGE_INTERSECT_NV_MASK = GLSLANG_STAGE_INTERSECT_MASK;
  static const GLSLANG_STAGE_ANYHIT_NV_MASK = GLSLANG_STAGE_ANYHIT_MASK;
  static const GLSLANG_STAGE_CLOSESTHIT_NV_MASK = GLSLANG_STAGE_CLOSESTHIT_MASK;
  static const GLSLANG_STAGE_MISS_NV_MASK = GLSLANG_STAGE_MISS_MASK;
  static const GLSLANG_STAGE_CALLABLE_NV_MASK = GLSLANG_STAGE_CALLABLE_MASK;
  static const GLSLANG_STAGE_TASK_NV_MASK = GLSLANG_STAGE_TASK_MASK;
  static const GLSLANG_STAGE_MESH_NV_MASK = GLSLANG_STAGE_MESH_MASK;

  final int value;
  const glslang_stage_mask_t(this.value);

  static glslang_stage_mask_t fromValue(int value) => switch (value) {
    1 => GLSLANG_STAGE_VERTEX_MASK,
    2 => GLSLANG_STAGE_TESSCONTROL_MASK,
    4 => GLSLANG_STAGE_TESSEVALUATION_MASK,
    8 => GLSLANG_STAGE_GEOMETRY_MASK,
    16 => GLSLANG_STAGE_FRAGMENT_MASK,
    32 => GLSLANG_STAGE_COMPUTE_MASK,
    64 => GLSLANG_STAGE_RAYGEN_MASK,
    128 => GLSLANG_STAGE_INTERSECT_MASK,
    256 => GLSLANG_STAGE_ANYHIT_MASK,
    512 => GLSLANG_STAGE_CLOSESTHIT_MASK,
    1024 => GLSLANG_STAGE_MISS_MASK,
    2048 => GLSLANG_STAGE_CALLABLE_MASK,
    4096 => GLSLANG_STAGE_TASK_MASK,
    8192 => GLSLANG_STAGE_MESH_MASK,
    8193 => GLSLANG_STAGE_MASK_COUNT,
    _ => throw ArgumentError('Unknown value for glslang_stage_mask_t: $value'),
  };

  @override
  String toString() {
    if (this == GLSLANG_STAGE_RAYGEN_MASK)
      return "glslang_stage_mask_t.GLSLANG_STAGE_RAYGEN_MASK, glslang_stage_mask_t.GLSLANG_STAGE_RAYGEN_NV_MASK";
    if (this == GLSLANG_STAGE_INTERSECT_MASK)
      return "glslang_stage_mask_t.GLSLANG_STAGE_INTERSECT_MASK, glslang_stage_mask_t.GLSLANG_STAGE_INTERSECT_NV_MASK";
    if (this == GLSLANG_STAGE_ANYHIT_MASK)
      return "glslang_stage_mask_t.GLSLANG_STAGE_ANYHIT_MASK, glslang_stage_mask_t.GLSLANG_STAGE_ANYHIT_NV_MASK";
    if (this == GLSLANG_STAGE_CLOSESTHIT_MASK)
      return "glslang_stage_mask_t.GLSLANG_STAGE_CLOSESTHIT_MASK, glslang_stage_mask_t.GLSLANG_STAGE_CLOSESTHIT_NV_MASK";
    if (this == GLSLANG_STAGE_MISS_MASK)
      return "glslang_stage_mask_t.GLSLANG_STAGE_MISS_MASK, glslang_stage_mask_t.GLSLANG_STAGE_MISS_NV_MASK";
    if (this == GLSLANG_STAGE_CALLABLE_MASK)
      return "glslang_stage_mask_t.GLSLANG_STAGE_CALLABLE_MASK, glslang_stage_mask_t.GLSLANG_STAGE_CALLABLE_NV_MASK";
    if (this == GLSLANG_STAGE_TASK_MASK)
      return "glslang_stage_mask_t.GLSLANG_STAGE_TASK_MASK, glslang_stage_mask_t.GLSLANG_STAGE_TASK_NV_MASK";
    if (this == GLSLANG_STAGE_MESH_MASK)
      return "glslang_stage_mask_t.GLSLANG_STAGE_MESH_MASK, glslang_stage_mask_t.GLSLANG_STAGE_MESH_NV_MASK";
    return super.toString();
  }
}

enum glslang_source_t {
  GLSLANG_SOURCE_NONE(0),
  GLSLANG_SOURCE_GLSL(1),
  GLSLANG_SOURCE_HLSL(2),
  GLSLANG_SOURCE_COUNT(3);

  final int value;
  const glslang_source_t(this.value);

  static glslang_source_t fromValue(int value) => switch (value) {
    0 => GLSLANG_SOURCE_NONE,
    1 => GLSLANG_SOURCE_GLSL,
    2 => GLSLANG_SOURCE_HLSL,
    3 => GLSLANG_SOURCE_COUNT,
    _ => throw ArgumentError('Unknown value for glslang_source_t: $value'),
  };
}

enum glslang_client_t {
  GLSLANG_CLIENT_NONE(0),
  GLSLANG_CLIENT_VULKAN(1),
  GLSLANG_CLIENT_OPENGL(2),
  GLSLANG_CLIENT_COUNT(3);

  final int value;
  const glslang_client_t(this.value);

  static glslang_client_t fromValue(int value) => switch (value) {
    0 => GLSLANG_CLIENT_NONE,
    1 => GLSLANG_CLIENT_VULKAN,
    2 => GLSLANG_CLIENT_OPENGL,
    3 => GLSLANG_CLIENT_COUNT,
    _ => throw ArgumentError('Unknown value for glslang_client_t: $value'),
  };
}

enum glslang_target_language_t {
  GLSLANG_TARGET_NONE(0),
  GLSLANG_TARGET_SPV(1),
  GLSLANG_TARGET_COUNT(2);

  final int value;
  const glslang_target_language_t(this.value);

  static glslang_target_language_t fromValue(int value) => switch (value) {
    0 => GLSLANG_TARGET_NONE,
    1 => GLSLANG_TARGET_SPV,
    2 => GLSLANG_TARGET_COUNT,
    _ => throw ArgumentError(
      'Unknown value for glslang_target_language_t: $value',
    ),
  };
}

enum glslang_target_client_version_t {
  GLSLANG_TARGET_VULKAN_1_0(4194304),
  GLSLANG_TARGET_VULKAN_1_1(4198400),
  GLSLANG_TARGET_VULKAN_1_2(4202496),
  GLSLANG_TARGET_VULKAN_1_3(4206592),
  GLSLANG_TARGET_VULKAN_1_4(4210688),
  GLSLANG_TARGET_OPENGL_450(450),
  GLSLANG_TARGET_CLIENT_VERSION_COUNT(6);

  final int value;
  const glslang_target_client_version_t(this.value);

  static glslang_target_client_version_t fromValue(int value) =>
      switch (value) {
        4194304 => GLSLANG_TARGET_VULKAN_1_0,
        4198400 => GLSLANG_TARGET_VULKAN_1_1,
        4202496 => GLSLANG_TARGET_VULKAN_1_2,
        4206592 => GLSLANG_TARGET_VULKAN_1_3,
        4210688 => GLSLANG_TARGET_VULKAN_1_4,
        450 => GLSLANG_TARGET_OPENGL_450,
        6 => GLSLANG_TARGET_CLIENT_VERSION_COUNT,
        _ => throw ArgumentError(
          'Unknown value for glslang_target_client_version_t: $value',
        ),
      };
}

enum glslang_target_language_version_t {
  GLSLANG_TARGET_SPV_1_0(65536),
  GLSLANG_TARGET_SPV_1_1(65792),
  GLSLANG_TARGET_SPV_1_2(66048),
  GLSLANG_TARGET_SPV_1_3(66304),
  GLSLANG_TARGET_SPV_1_4(66560),
  GLSLANG_TARGET_SPV_1_5(66816),
  GLSLANG_TARGET_SPV_1_6(67072),
  GLSLANG_TARGET_LANGUAGE_VERSION_COUNT(7);

  final int value;
  const glslang_target_language_version_t(this.value);

  static glslang_target_language_version_t fromValue(int value) =>
      switch (value) {
        65536 => GLSLANG_TARGET_SPV_1_0,
        65792 => GLSLANG_TARGET_SPV_1_1,
        66048 => GLSLANG_TARGET_SPV_1_2,
        66304 => GLSLANG_TARGET_SPV_1_3,
        66560 => GLSLANG_TARGET_SPV_1_4,
        66816 => GLSLANG_TARGET_SPV_1_5,
        67072 => GLSLANG_TARGET_SPV_1_6,
        7 => GLSLANG_TARGET_LANGUAGE_VERSION_COUNT,
        _ => throw ArgumentError(
          'Unknown value for glslang_target_language_version_t: $value',
        ),
      };
}

enum glslang_executable_t {
  GLSLANG_EX_VERTEX_FRAGMENT(0),
  GLSLANG_EX_FRAGMENT(1);

  final int value;
  const glslang_executable_t(this.value);

  static glslang_executable_t fromValue(int value) => switch (value) {
    0 => GLSLANG_EX_VERTEX_FRAGMENT,
    1 => GLSLANG_EX_FRAGMENT,
    _ => throw ArgumentError('Unknown value for glslang_executable_t: $value'),
  };
}

enum glslang_optimization_level_t {
  GLSLANG_OPT_NO_GENERATION(0),
  GLSLANG_OPT_NONE(1),
  GLSLANG_OPT_SIMPLE(2),
  GLSLANG_OPT_FULL(3),
  GLSLANG_OPT_LEVEL_COUNT(4);

  final int value;
  const glslang_optimization_level_t(this.value);

  static glslang_optimization_level_t fromValue(int value) => switch (value) {
    0 => GLSLANG_OPT_NO_GENERATION,
    1 => GLSLANG_OPT_NONE,
    2 => GLSLANG_OPT_SIMPLE,
    3 => GLSLANG_OPT_FULL,
    4 => GLSLANG_OPT_LEVEL_COUNT,
    _ => throw ArgumentError(
      'Unknown value for glslang_optimization_level_t: $value',
    ),
  };
}

enum glslang_texture_sampler_transform_mode_t {
  GLSLANG_TEX_SAMP_TRANS_KEEP(0),
  GLSLANG_TEX_SAMP_TRANS_UPGRADE_TEXTURE_REMOVE_SAMPLER(1),
  GLSLANG_TEX_SAMP_TRANS_COUNT(2);

  final int value;
  const glslang_texture_sampler_transform_mode_t(this.value);

  static glslang_texture_sampler_transform_mode_t fromValue(int value) =>
      switch (value) {
        0 => GLSLANG_TEX_SAMP_TRANS_KEEP,
        1 => GLSLANG_TEX_SAMP_TRANS_UPGRADE_TEXTURE_REMOVE_SAMPLER,
        2 => GLSLANG_TEX_SAMP_TRANS_COUNT,
        _ => throw ArgumentError(
          'Unknown value for glslang_texture_sampler_transform_mode_t: $value',
        ),
      };
}

enum glslang_messages_t {
  GLSLANG_MSG_DEFAULT_BIT(0),
  GLSLANG_MSG_RELAXED_ERRORS_BIT(1),
  GLSLANG_MSG_SUPPRESS_WARNINGS_BIT(2),
  GLSLANG_MSG_AST_BIT(4),
  GLSLANG_MSG_SPV_RULES_BIT(8),
  GLSLANG_MSG_VULKAN_RULES_BIT(16),
  GLSLANG_MSG_ONLY_PREPROCESSOR_BIT(32),
  GLSLANG_MSG_READ_HLSL_BIT(64),
  GLSLANG_MSG_CASCADING_ERRORS_BIT(128),
  GLSLANG_MSG_KEEP_UNCALLED_BIT(256),
  GLSLANG_MSG_HLSL_OFFSETS_BIT(512),
  GLSLANG_MSG_DEBUG_INFO_BIT(1024),
  GLSLANG_MSG_HLSL_ENABLE_16BIT_TYPES_BIT(2048),
  GLSLANG_MSG_HLSL_LEGALIZATION_BIT(4096),
  GLSLANG_MSG_HLSL_DX9_COMPATIBLE_BIT(8192),
  GLSLANG_MSG_BUILTIN_SYMBOL_TABLE_BIT(16384),
  GLSLANG_MSG_ENHANCED(32768),
  GLSLANG_MSG_ABSOLUTE_PATH(65536),
  GLSLANG_MSG_DISPLAY_ERROR_COLUMN(131072),
  GLSLANG_MSG_LINK_TIME_OPTIMIZATION_BIT(262144),
  GLSLANG_MSG_VALIDATE_CROSS_STAGE_IO_BIT(524288),
  GLSLANG_MSG_COUNT(524289);

  final int value;
  const glslang_messages_t(this.value);

  static glslang_messages_t fromValue(int value) => switch (value) {
    0 => GLSLANG_MSG_DEFAULT_BIT,
    1 => GLSLANG_MSG_RELAXED_ERRORS_BIT,
    2 => GLSLANG_MSG_SUPPRESS_WARNINGS_BIT,
    4 => GLSLANG_MSG_AST_BIT,
    8 => GLSLANG_MSG_SPV_RULES_BIT,
    16 => GLSLANG_MSG_VULKAN_RULES_BIT,
    32 => GLSLANG_MSG_ONLY_PREPROCESSOR_BIT,
    64 => GLSLANG_MSG_READ_HLSL_BIT,
    128 => GLSLANG_MSG_CASCADING_ERRORS_BIT,
    256 => GLSLANG_MSG_KEEP_UNCALLED_BIT,
    512 => GLSLANG_MSG_HLSL_OFFSETS_BIT,
    1024 => GLSLANG_MSG_DEBUG_INFO_BIT,
    2048 => GLSLANG_MSG_HLSL_ENABLE_16BIT_TYPES_BIT,
    4096 => GLSLANG_MSG_HLSL_LEGALIZATION_BIT,
    8192 => GLSLANG_MSG_HLSL_DX9_COMPATIBLE_BIT,
    16384 => GLSLANG_MSG_BUILTIN_SYMBOL_TABLE_BIT,
    32768 => GLSLANG_MSG_ENHANCED,
    65536 => GLSLANG_MSG_ABSOLUTE_PATH,
    131072 => GLSLANG_MSG_DISPLAY_ERROR_COLUMN,
    262144 => GLSLANG_MSG_LINK_TIME_OPTIMIZATION_BIT,
    524288 => GLSLANG_MSG_VALIDATE_CROSS_STAGE_IO_BIT,
    524289 => GLSLANG_MSG_COUNT,
    _ => throw ArgumentError('Unknown value for glslang_messages_t: $value'),
  };
}

enum glslang_reflection_options_t {
  GLSLANG_REFLECTION_DEFAULT_BIT(0),
  GLSLANG_REFLECTION_STRICT_ARRAY_SUFFIX_BIT(1),
  GLSLANG_REFLECTION_BASIC_ARRAY_SUFFIX_BIT(2),
  GLSLANG_REFLECTION_INTERMEDIATE_IOO_BIT(4),
  GLSLANG_REFLECTION_SEPARATE_BUFFERS_BIT(8),
  GLSLANG_REFLECTION_ALL_BLOCK_VARIABLES_BIT(16),
  GLSLANG_REFLECTION_UNWRAP_IO_BLOCKS_BIT(32),
  GLSLANG_REFLECTION_ALL_IO_VARIABLES_BIT(64),
  GLSLANG_REFLECTION_SHARED_STD140_SSBO_BIT(128),
  GLSLANG_REFLECTION_SHARED_STD140_UBO_BIT(256),
  GLSLANG_REFLECTION_COUNT(257);

  final int value;
  const glslang_reflection_options_t(this.value);

  static glslang_reflection_options_t fromValue(int value) => switch (value) {
    0 => GLSLANG_REFLECTION_DEFAULT_BIT,
    1 => GLSLANG_REFLECTION_STRICT_ARRAY_SUFFIX_BIT,
    2 => GLSLANG_REFLECTION_BASIC_ARRAY_SUFFIX_BIT,
    4 => GLSLANG_REFLECTION_INTERMEDIATE_IOO_BIT,
    8 => GLSLANG_REFLECTION_SEPARATE_BUFFERS_BIT,
    16 => GLSLANG_REFLECTION_ALL_BLOCK_VARIABLES_BIT,
    32 => GLSLANG_REFLECTION_UNWRAP_IO_BLOCKS_BIT,
    64 => GLSLANG_REFLECTION_ALL_IO_VARIABLES_BIT,
    128 => GLSLANG_REFLECTION_SHARED_STD140_SSBO_BIT,
    256 => GLSLANG_REFLECTION_SHARED_STD140_UBO_BIT,
    257 => GLSLANG_REFLECTION_COUNT,
    _ => throw ArgumentError(
      'Unknown value for glslang_reflection_options_t: $value',
    ),
  };
}

enum glslang_profile_t {
  GLSLANG_BAD_PROFILE(0),
  GLSLANG_NO_PROFILE(1),
  GLSLANG_CORE_PROFILE(2),
  GLSLANG_COMPATIBILITY_PROFILE(4),
  GLSLANG_ES_PROFILE(8),
  GLSLANG_PROFILE_COUNT(9);

  final int value;
  const glslang_profile_t(this.value);

  static glslang_profile_t fromValue(int value) => switch (value) {
    0 => GLSLANG_BAD_PROFILE,
    1 => GLSLANG_NO_PROFILE,
    2 => GLSLANG_CORE_PROFILE,
    4 => GLSLANG_COMPATIBILITY_PROFILE,
    8 => GLSLANG_ES_PROFILE,
    9 => GLSLANG_PROFILE_COUNT,
    _ => throw ArgumentError('Unknown value for glslang_profile_t: $value'),
  };
}

enum glslang_shader_options_t {
  GLSLANG_SHADER_DEFAULT_BIT(0),
  GLSLANG_SHADER_AUTO_MAP_BINDINGS(1),
  GLSLANG_SHADER_AUTO_MAP_LOCATIONS(2),
  GLSLANG_SHADER_VULKAN_RULES_RELAXED(4),
  GLSLANG_SHADER_COUNT(5);

  final int value;
  const glslang_shader_options_t(this.value);

  static glslang_shader_options_t fromValue(int value) => switch (value) {
    0 => GLSLANG_SHADER_DEFAULT_BIT,
    1 => GLSLANG_SHADER_AUTO_MAP_BINDINGS,
    2 => GLSLANG_SHADER_AUTO_MAP_LOCATIONS,
    4 => GLSLANG_SHADER_VULKAN_RULES_RELAXED,
    5 => GLSLANG_SHADER_COUNT,
    _ => throw ArgumentError(
      'Unknown value for glslang_shader_options_t: $value',
    ),
  };
}

enum glslang_resource_type_t {
  GLSLANG_RESOURCE_TYPE_SAMPLER(0),
  GLSLANG_RESOURCE_TYPE_TEXTURE(1),
  GLSLANG_RESOURCE_TYPE_IMAGE(2),
  GLSLANG_RESOURCE_TYPE_UBO(3),
  GLSLANG_RESOURCE_TYPE_SSBO(4),
  GLSLANG_RESOURCE_TYPE_UAV(5),
  GLSLANG_RESOURCE_TYPE_COMBINED_SAMPLER(6),
  GLSLANG_RESOURCE_TYPE_AS(7),
  GLSLANG_RESOURCE_TYPE_TENSOR(8),
  GLSLANG_RESOURCE_TYPE_COUNT(9);

  final int value;
  const glslang_resource_type_t(this.value);

  static glslang_resource_type_t fromValue(int value) => switch (value) {
    0 => GLSLANG_RESOURCE_TYPE_SAMPLER,
    1 => GLSLANG_RESOURCE_TYPE_TEXTURE,
    2 => GLSLANG_RESOURCE_TYPE_IMAGE,
    3 => GLSLANG_RESOURCE_TYPE_UBO,
    4 => GLSLANG_RESOURCE_TYPE_SSBO,
    5 => GLSLANG_RESOURCE_TYPE_UAV,
    6 => GLSLANG_RESOURCE_TYPE_COMBINED_SAMPLER,
    7 => GLSLANG_RESOURCE_TYPE_AS,
    8 => GLSLANG_RESOURCE_TYPE_TENSOR,
    9 => GLSLANG_RESOURCE_TYPE_COUNT,
    _ => throw ArgumentError(
      'Unknown value for glslang_resource_type_t: $value',
    ),
  };
}

final class glslang_shader_s extends ffi.Opaque {}

typedef glslang_shader_t = glslang_shader_s;

final class glslang_program_s extends ffi.Opaque {}

typedef glslang_program_t = glslang_program_s;

final class glslang_mapper_s extends ffi.Opaque {}

typedef glslang_mapper_t = glslang_mapper_s;

final class glslang_resolver_s extends ffi.Opaque {}

typedef glslang_resolver_t = glslang_resolver_s;

final class glslang_version_s extends ffi.Struct {
  @ffi.Int()
  external int major;

  @ffi.Int()
  external int minor;

  @ffi.Int()
  external int patch;

  external ffi.Pointer<ffi.Char> flavor;
}

typedef glslang_version_t = glslang_version_s;

final class glslang_limits_s extends ffi.Struct {
  @ffi.Bool()
  external bool non_inductive_for_loops;

  @ffi.Bool()
  external bool while_loops;

  @ffi.Bool()
  external bool do_while_loops;

  @ffi.Bool()
  external bool general_uniform_indexing;

  @ffi.Bool()
  external bool general_attribute_matrix_vector_indexing;

  @ffi.Bool()
  external bool general_varying_indexing;

  @ffi.Bool()
  external bool general_sampler_indexing;

  @ffi.Bool()
  external bool general_variable_indexing;

  @ffi.Bool()
  external bool general_constant_matrix_vector_indexing;
}

typedef glslang_limits_t = glslang_limits_s;

final class UnnamedUnion extends ffi.Union {
  @ffi.Int()
  external int max_dual_source_draw_buffers_ext;

  @ffi.Int()
  external int maxDualSourceDrawBuffersEXT;
}

final class glslang_resource_s extends ffi.Struct {
  @ffi.Int()
  external int max_lights;

  @ffi.Int()
  external int max_clip_planes;

  @ffi.Int()
  external int max_texture_units;

  @ffi.Int()
  external int max_texture_coords;

  @ffi.Int()
  external int max_vertex_attribs;

  @ffi.Int()
  external int max_vertex_uniform_components;

  @ffi.Int()
  external int max_varying_floats;

  @ffi.Int()
  external int max_vertex_texture_image_units;

  @ffi.Int()
  external int max_combined_texture_image_units;

  @ffi.Int()
  external int max_texture_image_units;

  @ffi.Int()
  external int max_fragment_uniform_components;

  @ffi.Int()
  external int max_draw_buffers;

  @ffi.Int()
  external int max_vertex_uniform_vectors;

  @ffi.Int()
  external int max_varying_vectors;

  @ffi.Int()
  external int max_fragment_uniform_vectors;

  @ffi.Int()
  external int max_vertex_output_vectors;

  @ffi.Int()
  external int max_fragment_input_vectors;

  @ffi.Int()
  external int min_program_texel_offset;

  @ffi.Int()
  external int max_program_texel_offset;

  @ffi.Int()
  external int max_clip_distances;

  @ffi.Int()
  external int max_compute_work_group_count_x;

  @ffi.Int()
  external int max_compute_work_group_count_y;

  @ffi.Int()
  external int max_compute_work_group_count_z;

  @ffi.Int()
  external int max_compute_work_group_size_x;

  @ffi.Int()
  external int max_compute_work_group_size_y;

  @ffi.Int()
  external int max_compute_work_group_size_z;

  @ffi.Int()
  external int max_compute_uniform_components;

  @ffi.Int()
  external int max_compute_texture_image_units;

  @ffi.Int()
  external int max_compute_image_uniforms;

  @ffi.Int()
  external int max_compute_atomic_counters;

  @ffi.Int()
  external int max_compute_atomic_counter_buffers;

  @ffi.Int()
  external int max_varying_components;

  @ffi.Int()
  external int max_vertex_output_components;

  @ffi.Int()
  external int max_geometry_input_components;

  @ffi.Int()
  external int max_geometry_output_components;

  @ffi.Int()
  external int max_fragment_input_components;

  @ffi.Int()
  external int max_image_units;

  @ffi.Int()
  external int max_combined_image_units_and_fragment_outputs;

  @ffi.Int()
  external int max_combined_shader_output_resources;

  @ffi.Int()
  external int max_image_samples;

  @ffi.Int()
  external int max_vertex_image_uniforms;

  @ffi.Int()
  external int max_tess_control_image_uniforms;

  @ffi.Int()
  external int max_tess_evaluation_image_uniforms;

  @ffi.Int()
  external int max_geometry_image_uniforms;

  @ffi.Int()
  external int max_fragment_image_uniforms;

  @ffi.Int()
  external int max_combined_image_uniforms;

  @ffi.Int()
  external int max_geometry_texture_image_units;

  @ffi.Int()
  external int max_geometry_output_vertices;

  @ffi.Int()
  external int max_geometry_total_output_components;

  @ffi.Int()
  external int max_geometry_uniform_components;

  @ffi.Int()
  external int max_geometry_varying_components;

  @ffi.Int()
  external int max_tess_control_input_components;

  @ffi.Int()
  external int max_tess_control_output_components;

  @ffi.Int()
  external int max_tess_control_texture_image_units;

  @ffi.Int()
  external int max_tess_control_uniform_components;

  @ffi.Int()
  external int max_tess_control_total_output_components;

  @ffi.Int()
  external int max_tess_evaluation_input_components;

  @ffi.Int()
  external int max_tess_evaluation_output_components;

  @ffi.Int()
  external int max_tess_evaluation_texture_image_units;

  @ffi.Int()
  external int max_tess_evaluation_uniform_components;

  @ffi.Int()
  external int max_tess_patch_components;

  @ffi.Int()
  external int max_patch_vertices;

  @ffi.Int()
  external int max_tess_gen_level;

  @ffi.Int()
  external int max_viewports;

  @ffi.Int()
  external int max_vertex_atomic_counters;

  @ffi.Int()
  external int max_tess_control_atomic_counters;

  @ffi.Int()
  external int max_tess_evaluation_atomic_counters;

  @ffi.Int()
  external int max_geometry_atomic_counters;

  @ffi.Int()
  external int max_fragment_atomic_counters;

  @ffi.Int()
  external int max_combined_atomic_counters;

  @ffi.Int()
  external int max_atomic_counter_bindings;

  @ffi.Int()
  external int max_vertex_atomic_counter_buffers;

  @ffi.Int()
  external int max_tess_control_atomic_counter_buffers;

  @ffi.Int()
  external int max_tess_evaluation_atomic_counter_buffers;

  @ffi.Int()
  external int max_geometry_atomic_counter_buffers;

  @ffi.Int()
  external int max_fragment_atomic_counter_buffers;

  @ffi.Int()
  external int max_combined_atomic_counter_buffers;

  @ffi.Int()
  external int max_atomic_counter_buffer_size;

  @ffi.Int()
  external int max_transform_feedback_buffers;

  @ffi.Int()
  external int max_transform_feedback_interleaved_components;

  @ffi.Int()
  external int max_cull_distances;

  @ffi.Int()
  external int max_combined_clip_and_cull_distances;

  @ffi.Int()
  external int max_samples;

  @ffi.Int()
  external int max_mesh_output_vertices_nv;

  @ffi.Int()
  external int max_mesh_output_primitives_nv;

  @ffi.Int()
  external int max_mesh_work_group_size_x_nv;

  @ffi.Int()
  external int max_mesh_work_group_size_y_nv;

  @ffi.Int()
  external int max_mesh_work_group_size_z_nv;

  @ffi.Int()
  external int max_task_work_group_size_x_nv;

  @ffi.Int()
  external int max_task_work_group_size_y_nv;

  @ffi.Int()
  external int max_task_work_group_size_z_nv;

  @ffi.Int()
  external int max_mesh_view_count_nv;

  @ffi.Int()
  external int max_mesh_output_vertices_ext;

  @ffi.Int()
  external int max_mesh_output_primitives_ext;

  @ffi.Int()
  external int max_mesh_work_group_size_x_ext;

  @ffi.Int()
  external int max_mesh_work_group_size_y_ext;

  @ffi.Int()
  external int max_mesh_work_group_size_z_ext;

  @ffi.Int()
  external int max_task_work_group_size_x_ext;

  @ffi.Int()
  external int max_task_work_group_size_y_ext;

  @ffi.Int()
  external int max_task_work_group_size_z_ext;

  @ffi.Int()
  external int max_mesh_view_count_ext;

  external UnnamedUnion unnamed;

  external glslang_limits_t limits;
}

typedef glslang_resource_t = glslang_resource_s;

final class glsl_include_result_s extends ffi.Struct {
  external ffi.Pointer<ffi.Char> header_name;

  external ffi.Pointer<ffi.Char> header_data;

  @ffi.Size()
  external int header_length;
}

typedef glsl_include_result_t = glsl_include_result_s;
typedef glsl_include_local_funcFunction =
    ffi.Pointer<glsl_include_result_t> Function(
      ffi.Pointer<ffi.Void> ctx,
      ffi.Pointer<ffi.Char> header_name,
      ffi.Pointer<ffi.Char> includer_name,
      ffi.Size include_depth,
    );
typedef Dartglsl_include_local_funcFunction =
    ffi.Pointer<glsl_include_result_t> Function(
      ffi.Pointer<ffi.Void> ctx,
      ffi.Pointer<ffi.Char> header_name,
      ffi.Pointer<ffi.Char> includer_name,
      int include_depth,
    );
typedef glsl_include_local_func =
    ffi.Pointer<ffi.NativeFunction<glsl_include_local_funcFunction>>;
typedef glsl_include_system_funcFunction =
    ffi.Pointer<glsl_include_result_t> Function(
      ffi.Pointer<ffi.Void> ctx,
      ffi.Pointer<ffi.Char> header_name,
      ffi.Pointer<ffi.Char> includer_name,
      ffi.Size include_depth,
    );
typedef Dartglsl_include_system_funcFunction =
    ffi.Pointer<glsl_include_result_t> Function(
      ffi.Pointer<ffi.Void> ctx,
      ffi.Pointer<ffi.Char> header_name,
      ffi.Pointer<ffi.Char> includer_name,
      int include_depth,
    );
typedef glsl_include_system_func =
    ffi.Pointer<ffi.NativeFunction<glsl_include_system_funcFunction>>;
typedef glsl_free_include_result_funcFunction =
    ffi.Int Function(
      ffi.Pointer<ffi.Void> ctx,
      ffi.Pointer<glsl_include_result_t> result,
    );
typedef Dartglsl_free_include_result_funcFunction =
    int Function(
      ffi.Pointer<ffi.Void> ctx,
      ffi.Pointer<glsl_include_result_t> result,
    );
typedef glsl_free_include_result_func =
    ffi.Pointer<ffi.NativeFunction<glsl_free_include_result_funcFunction>>;

final class glsl_include_callbacks_s extends ffi.Struct {
  external glsl_include_system_func include_system;

  external glsl_include_local_func include_local;

  external glsl_free_include_result_func free_include_result;
}

typedef glsl_include_callbacks_t = glsl_include_callbacks_s;

final class glslang_input_s extends ffi.Struct {
  @ffi.UnsignedInt()
  external int languageAsInt;

  glslang_source_t get language => glslang_source_t.fromValue(languageAsInt);

  @ffi.UnsignedInt()
  external int stageAsInt;

  glslang_stage_t get stage => glslang_stage_t.fromValue(stageAsInt);

  @ffi.UnsignedInt()
  external int clientAsInt;

  glslang_client_t get client => glslang_client_t.fromValue(clientAsInt);

  @ffi.UnsignedInt()
  external int client_versionAsInt;

  glslang_target_client_version_t get client_version =>
      glslang_target_client_version_t.fromValue(client_versionAsInt);

  @ffi.UnsignedInt()
  external int target_languageAsInt;

  glslang_target_language_t get target_language =>
      glslang_target_language_t.fromValue(target_languageAsInt);

  @ffi.UnsignedInt()
  external int target_language_versionAsInt;

  glslang_target_language_version_t get target_language_version =>
      glslang_target_language_version_t.fromValue(target_language_versionAsInt);

  /// Shader source code
  external ffi.Pointer<ffi.Char> code;

  @ffi.Int()
  external int default_version;

  @ffi.UnsignedInt()
  external int default_profileAsInt;

  glslang_profile_t get default_profile =>
      glslang_profile_t.fromValue(default_profileAsInt);

  @ffi.Int()
  external int force_default_version_and_profile;

  @ffi.Int()
  external int forward_compatible;

  @ffi.UnsignedInt()
  external int messagesAsInt;

  glslang_messages_t get messages =>
      glslang_messages_t.fromValue(messagesAsInt);

  external ffi.Pointer<glslang_resource_t> resource;

  external glsl_include_callbacks_t callbacks;

  external ffi.Pointer<ffi.Void> callbacks_ctx;
}

typedef glslang_input_t = glslang_input_s;

final class glslang_spv_options_s extends ffi.Struct {
  @ffi.Bool()
  external bool generate_debug_info;

  @ffi.Bool()
  external bool strip_debug_info;

  @ffi.Bool()
  external bool disable_optimizer;

  @ffi.Bool()
  external bool optimize_size;

  @ffi.Bool()
  external bool disassemble;

  @ffi.Bool()
  external bool validate;

  @ffi.Bool()
  external bool emit_nonsemantic_shader_debug_info;

  @ffi.Bool()
  external bool emit_nonsemantic_shader_debug_source;

  @ffi.Bool()
  external bool compile_only;

  @ffi.Bool()
  external bool optimize_allow_expanded_id_bound;
}

typedef glslang_spv_options_t = glslang_spv_options_s;
